# Your Name or Company
title: Sungbin Lim

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.


 # A brief blurb about yourself
 content: Master course in Information and Communication Engineering, HGU (2022~)\nB.S in Computer Science and Electrical Engineering, HGU (2022)\n\nhttps://sungbin.github.io/\n313 Oseok Hall, Handong Global Univ. 558 Handong-ro, Buk-gu, Pohang, Gyeongbuk, South Korea 37554
