# Your Name or Company
title: Uni Kravitz

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: 
 content: Master course in Information and Communication Engineering, HGU (2022~) B.S in Computer Science and Electrical Engineering, HGU (2022) https://sungbin.github.io/ 313 Oseok Hall, Handong Global Univ. 558 Handong-ro, Buk-gu, Pohang, Gyeongbuk, South Korea 37554

# Add your social links
social:
  - platform: github
    url: https://github.com/sungbin
  - platform: facebook
    url: https://facebook.com/brianmaierjr
  - platform: twitter
    url: https://twitter.com/brianmaierjr
  - platform: linkedin
    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
